bump kernel and add a new option support fan control
tpwrules/nixos-apple-silicon pull request #250
Opened 2024-11-19 20:01 UTC by marcusramberg

- **linux-asahi: asahi-6.10.6-1 -> asahi-6.10.9.3**
- **modules/kernel: add option to enable hwmon fan control**

Tested this on my mac studio m1, being able to slow down the fan makes a huge noise difference.

2024-11-22 11:03 UTC, flokli requested changes

2024-11-22 11:03 UTC, flokli commented on apple-silicon-support/modules/kernel/default.nix
> +      options macsmc_hwmon melt_my_mac=1
From marcan42 on [Reddit](https://www.reddit.com/r/AsahiLinux/comments/1g15m8f/comment/lrjchuz/):

> You need to set the melt_my_mac=1 option for the macsmc-hwmon module to enable fan control. This is unsupported and at your own risk. The default firmware fan control is supposed to be sufficient to avoid throttling. 

I'm not sure this is something we should expose in the module system with at least the same amount of caveats attached - and that point people can just add this line to their config directly, without adding the module option at all.

2024-11-22 11:17 UTC, flokli commented
There's been a few other kernel bumps since then (to 6.11 too), this could probably be re-rolled separately.

2024-11-30 19:37 UTC, tpwrules commented
Thanks for the effort, but I am not interested in so easily enabling an option so direly labeled. This should be easy for users to add to their own config if they so desired.

2024-11-30 19:37 UTC, closed without merging